### ISSUE TITLE
Need to import padStart/padEnd shims

### ISSUE THREAD

**Issue by goatslacker** [MailOnline/jest-tap-reporter#39]
Trying to use this on a Node version that doesn't have this sort of support yet so it would be great if the package provided shims for these functions so that the reporter doesn't fail when the test runner is complete.

I can put up a PR if you'd like.

https://www.npmjs.com/package/string.prototype.padstart
https://www.npmjs.com/package/string.prototype.padend

**Comment by streamich** [comment]
Yes, please PR would be great.

https://github.com/MailOnline/jest-tap-reporter/issues/17

**Comment by streamich** [comment]
Fixed in https://github.com/MailOnline/jest-tap-reporter/pull/43
